resources: {
    en: {
        translations: {
            "Super sale 48% off",
            "winter-jacket",
            "Winter Jacket Front",
            "Winter Jacket Back",
            "Uniqlo",
            "cotton-t-shirt",
            "Stylish winter jacket made from premium materials to keep you warm and comfortable.",
            "T-Shirt Front",
            "T-Shirt Back",
            "A comfortable and stylish cotton t-shirt perfect for casual outings and daily wear.",
            "H&M",
            "Backpack Side",
            "Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            "sports-watch",
            "Sports Watch Side",
            "Sketches",
            "A sleek sports watch perfect for athletes and everyday wear. Water-resistant and stylish.",
            "accessories",
            "Adidas",
            "running-shoes",
            "Running Shoes Side",
            "projector"
            "Comfortable running shoes for all-day wear. Made with durable materials to last longer.",
            "shoes"
            "Nike",
            "Sale",
            "backpack",
            "Backpack Side",
            "Paper",
            "Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus."
            "Zara",
            "clothes",
            "Trait-Tex Jumbo Roving Yarn",
            "Utrecht Artists' Imperfect Oil Paint Tubes and Cans",
            "Wood Craft Supplies",
            "2025 Staples 5 x 8 Weekly & Monthly",
            "Homenations 36W Wood/- Metal Student Desk With",
            "HP 15.6 Laptop, AMD Ryzen 3, Al Enabled, 8GB",
            "Trait-Tex Jumbo Roving Yarn, Jumbo Roving Yarn",
            "Utrecht Artists' Imperfect Oil Paint Tubes and Cans",
            "Lenovo Tab M11 FHD LCD Tablet, 1920 x 1200, MTK",
            "2025 Staples 5 x 8 Weekly & Monthly",
            "Homenations 36W Wood/- Metal Student Desk With",
            "HP 15.6 Laptop, AMD Ryzen 3, Al Enabled, 8GB",
            "WorkPro 100 Series Ergonomic Mesh/Mesh",
            "Accessory Innovations Stitch Full Size 16 inch",
            "Epson Workforce ES-500W II Wireless Color",
            "Premium Colored Pencils 24 Count, SOft Core, Multi-",
            "TMY Mini Projector, UpgradedBluetoothProject-",
            "Hammermill Copy Plus 8.5X11 Copy Paper, 20...",
            "40 items": "40 items",
            "Water Color": "Water Color",
            "Add to Cart": "Add to Cart",
            "Out of Stock": "Out of Stock",
            'NEW ARRIVAL': 'NEW ARRIVAL',
            "SPECIAL": "SPECIAL",
            "FEATURED": "FEATURED",
            "Collaboration":"Collaboration",
            "We Collaborate With 30+ Schools In Saudi Arabia":"We Collaborate With 30+ Schools In Saudi Arabia",
            'Scale Set':'Scale Set',
            'Paper Pads':'Paper Pads',
            'Project Files':'Project Files',
            'Cups':'Cups',
            'Dress':'Dress',
            'Scales':'Scales',
            'Files':'Files',
            'Coffee Mug':'Coffee Mug',
            'Hand Book of AI':'Hand Book of AI',
            'Water Color Set':'Water Color Set',
            'School Dress':'School Dress',
            'Bag':'Bag',
            'School Bag':'School Bag',
            "on sale":"on sale",
            'special products': 'special products',
            'exclusive products': 'exclusive products',
            'Watercolors Cake Set': 'Watercolors Cake Set',
            'MFD kits': 'MFD kits',
            'Bags & more': 'Bags & more',
            'Stationary': 'Stationary',
            'Graduation': "graduation",
            'Unique Products You Wont Find Anywhere Else !': 'Unique Products You Wont Find Anywhere Else !',
            'Books': 'Books',
            'topbar_title': 'Welcome to Our store Multikart',
            'call_us': 'Call Us',
            'Home': 'Home',
            'Smarter Schools': 'Smarter Schools',
            'features': 'features',
            'new': 'new',
            "Blogs": "Blogs",
            'blog_left_sidebar': 'left sidebar',
            'blog_right_sidebar': 'right sidebar',
            'blog_detail': 'blog detail',
            'category_left_sidebar': 'left sidebar',
            'category_right_sidebar': 'right sidebar',
            'category_no_sidebar': 'no sidebar',
            'category_metro': 'metro',
            'category_full_width': 'full width',
            'Products': 'Products',
            'left_sidebar': 'left sidebar',
            'right_sidebar': 'right sidebar',
            'no_sidebar': 'no sidebar',
            'three_col_thumbnail_left': 'Thumbnail left',
            'three_col_thumbnail_right': 'Thumbnail right',
            'thumbnail_below': 'thumbnail below',
            'accordian_details': 'accordian details',
            'thumbnail_left': 'image left',
            'thumbnail_right': 'image right',
            'vertical_tab': 'vertical tab',
            'Pages': 'Pages',
            'about_us': 'about us',
            "about": "about",
            'lookbook': 'lookbook',
            'login': 'login',
            'register': 'register',
            'logout': 'Logout',
            'search': 'search',
            'wishlist': 'wishlist',
            'cart': 'cart',
            'collection': 'collection',
            'forget_password': 'forget password',
            'contact': 'contact',
            'checkout': 'checkout',
            'compare': 'compare',
            'order_success': 'order_success',
            'dashboard': 'Dashboard',
            'FAQ': 'FAQ',
            'Shop': 'Shop',
            'mens_fashion': 'mens fashion',
            'top': 'top',
            'bottom': 'bottom',
            'ethic_wear': 'ethic wear',
            'sports_wear': 'sports wear',
            'shirts': 'shirts',
            'women_fashion': 'womens fashion',
            'dresses': 'dresses',
            'skirts': 'skirts',
            'westarn_wear': 'westarn wear',
            'ethnic_wear': 'ethnic wear',
            'sport_wear': 'aport wear',
            'bottom_wear': 'bottom wear',
            'kids_fashion': 'kidss fashion',
            'accessories': 'Accessories',
            'fashion_jewellery': 'Fashion Jewellery',
            'caps_and_hats': 'caps and hats',
            'precious_jewellery': 'precious jewellery',
            'necklaces': 'necklaces',
            'earrings': 'earrings',
            'rings_wrist_wear': 'rings & wrist wear',
            'men_accessories': 'mens accessories',
            'ties': 'ties',
            'cufflinks': 'cufflinks',
            'pockets_squares': 'pockets squares',
            'helmets': 'helmets',
            'scarves': 'scarves',
            'phone_cases': 'phone cases',
            'my_account': 'My Account',
            'fashion': 'Fashion',
            'beauty': 'Beauty',
            'electronic': 'Electronic',
            'furniture': 'Furniture',
            'kids': 'Kids',
            'pets': 'Pets',
            'vegetables': 'Vegetables',
            'watch': 'Watch',
            'theme_elements': 'theme elements',
            'element_title': 'element title',
            'collection_banner': 'collection banner',
            'home_slider': 'home slider',
            'category': 'category',
            'service': 'service',
            'image_size_ratio': 'image size ratio',
            'product_elements': 'product elements',
            'product_box': 'product box',
            'product_slider': 'product slider',
            'no_slider': 'no slider',
            'multi_slider': 'multi slider',
            'tab': 'tab',
            'email_template': 'email template',
            'portfolio': 'portfolio',
            'portfolio_grid_2': 'portfolio grid 2',
            'portfolio_grid_3': 'portfolio grid 3',
            'portfolio_grid_4': 'portfolio grid 4',
            'portfolio_masonary_2': 'masonary 2',
            'portfolio_masonary_3': 'masonary 3',
            'portfolio_masonary_4': 'masonary 4',
            'portfolio_masonary_full': 'masonary full width',
            "Secure delivery without contacting the courier":"Secure delivery without contacting the courier"
        }
    },

    ar: {
        translations: {
            "Super sale 48% off":"تخفيضات هائلة بخصم 48%",
            "winter-jacket":"سترة الشتاء",
            "Winter Jacket Front":"سترة الشتاء الجبهة",
            "Winter Jacket Back":"سترة الشتاء مرة أخرى",
            "Stylish winter jacket made from premium materials to keep you warm and comfortable.":"سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
            "Uniqlo":"يائس",
            "cotton-t-shirt":"تي شيرت قطن",
            "T-Shirt Front":"تي شيرت أمامي",
            "T-Shirt Back":"تي شيرت الظهر", 
            "A comfortable and stylish cotton t-shirt perfect for casual outings and daily wear.":"تي شيرت قطني مريح وأنيق مثالي للنزهات الكاجوال والارتداء اليومي.",
            "H&M":"اتش اند ام",
            "Backpack Side":"جانب حقيبة الظهر",
            "Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.":"لكن الحاجة، قبل volputate volutpat، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
            "sports-watch":"ساعة رياضية",
            "Sports Watch Side":"جانب الساعات الرياضية",
            "Sketches":"اسكتشات",
            "A sleek sports watch perfect for athletes and everyday wear. Water-resistant and stylish.":"ساعة رياضية أنيقة مثالية للرياضيين والارتداء اليومي. مقاومة للماء وأنيقة.",
            "accessories":"مُكَمِّلات",
            "Adidas":"أديداس",
            "running-shoes":"أحذية الجري",
            "Running Shoes Side":"جانب من أحذية الجري",
            "projector":"جهاز عرض",
            "Comfortable running shoes for all-day wear. Made with durable materials to last longer.":"حذاء جري مريح للارتداء طوال اليوم. مصنوعة من مواد متينة لتدوم لفترة أطول.",
            "shoes":"أحذية",
            "Nike":"نايك",
            "Sale","أُوكَازيُون",
            "backpack":"حقيبة ظهر",
            "Backpack Side":"جانب حقيبة الظهر",
            "Paper":"ورق",
            "Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.":"لكن الحاجة، قبل volputate volutpat، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
            "clothes":"ملابس",
            "Zara":"زارا",
            "Trait-Tex Jumbo Roving Yarn":"خيوط ترايت تكس جامبو المتجولة",
            "Utrecht Artists' Imperfect Oil Paint Tubes and Cans":"أنابيب وعلب الطلاء الزيتي غير الكاملة لفناني أوتريخت",
            "Wood Craft Supplies":"لوازم الحرف الخشبية"
            "2025 Staples 5 x 8 Weekly & Monthly":"2025 دبابيس 5 × 8 أسبوعية وشهرية",
            "Homenations 36W Wood/- Metal Student Desk With":"Homenations 36 بوصة عرض خشب/- مكتب طلاب معدني مع",
            "HP 15.6 Laptop, AMD Ryzen 3, Al Enabled, 8GB":"",
            "Trait-Tex Jumbo Roving Yarn, Jumbo Roving Yarn":"غزل ترايت تكس جامبو المتجول، غزل جامبو متجول",
            "Utrecht Artists' Imperfect Oil Paint Tubes and Cans":"أنابيب وعلب الطلاء الزيتي غير الكاملة لفناني أوتريخت",
            "Lenovo Tab M11 FHD LCD Tablet, 1920 x 1200, MTK":"تابلت لينوفو تاب M11 بوصة فل اتش دي ال سي دي، 1920 × 1200، MTK",
            "2025 Staples 5 x 8 Weekly & Monthly":"2025 دبابيس 5 × 8 أسبوعية وشهرية",
            "Homenations 36W Wood/- Metal Student Desk With":"مكتب طالب خشبي/معدني بعرض 36 بوصة من Homenations مع",
            "HP 15.6 Laptop, AMD Ryzen 3, Al Enabled, 8GB":"كمبيوتر محمول HP مقاس 15.6 بوصة، معالج AMD Ryzen 3، مُمكّن، سعة 8 جيجابايت",
            "WorkPro 100 Series Ergonomic Mesh/Mesh":"شبكة/شبكة مريحة من سلسلة WorkPro 100",
            "Accessory Innovations Stitch Full Size 16 inch":"ابتكارات الإكسسوارات غرزة كاملة الحجم 16 بوصة",
            "Epson Workforce ES-500W II Wireless Color":"اللون اللاسلكي Epson Workforce ES-500W II",
            "Premium Colored Pencils 24 Count, SOft Core, Multi-":"أقلام رصاص ملونة ممتازة، عدد 24، ناعمة الملمس، متعددة الألوان",
            "TMY Mini Projector, UpgradedBluetoothProject-":"جهاز عرض TMY صغير، مشروع بلوتوث مطور-"
            "Hammermill Copy Plus 8.5X11 Copy Paper, 20...":"ورق نسخ هامرميل كوبي بلس مقاس 8.5 بوصة × 11 بوصة، 20...",
            "Secure delivery without contacting the courier":"تسليم آمن دون الاتصال بالبريد السريع",
            "Out of Stock": "إنتهى من المخزن",
            "Collaboration":"تعاون",
            "We Collaborate With 30+ Schools In Saudi Arabia" :"نحن نتعاون مع أكثر من 30 مدرسة في المملكة العربية السعودية" ,           
            'Scale Set':'مجموعة النطاق',
            'Paper Pads':'منصات الورق',
            'Project Files':'ملفات المشروع',
            'Cups':'الكؤوس',
            'Dress':'فستان',
            'Scales':'المقاييس',
            'Paper Pads':'منصات الورق',
            'Files':'ملفات',
            'Coffee Mug':'كوب قهوة',
            'Hand Book of AI':'كتاب اليد للذكاء الاصطناعي',
            'Water Color Set':'مجموعة ألوان مائية',
            'School Dress':'فستان المدرسة',
            'Bag':'شنطة',
            'School Bag':'حقيبة مدرسية',
            'Enter your email': 'أدخل بريدك الإلكتروني',
            'new': 'جديد',
            "Fax: 123456":"فاكس: 123456",
            "on sale":"للبيع",
            "seller stores":"متاجر البائع",
            '': '',
            'School Corner': 'ركن المدرسة',
            'School Supplies': 'اللوازم المدرسية',
            'SPECIAL': 'خاص',
            'FEATURED': 'مميز',
            'NEW ARRIVAL': 'وصول جديد',
            'special products': 'منتجات خاصة',
            'exclusive products': 'منتجات حصرية',
            'fitted dress': 'فستان مناسب',
            'belted top': 'أعلى مربوط',
            'Add to Cart': 'أضف إلى السلة',
            'Watercolors Cake Set': 'مجموعة كعكة الألوان المائية',
            'Exclusive on edumall': 'حصريا على ايدومال',
            '40 items': '٤٠ مادة',
            'Stationary': 'ثابتة',
            'Bags & more': 'حقائب وأكثر',
            'MFD kits': 'مجموعات MFD',
            'Electronics & more': 'الالكترونيات وأكثر',
            'Printed papers': 'الأوراق المطبوعة',
            'Wax & moulds': 'الشمع والقوالب',
            'Graduation': 'تخرُّج',
            'Unique Products You Wont Find Anywhere Else !': 'منتجات فريدة لن تجدها في أي مكان آخر!',
            'topbar_title': 'مرحبًا بكم في متجرنا مولتي كارت',
            'call_us': 'اتصل بنا',
            'Home': 'الصفحة الرئيسية',
            'Smarter Schools': 'المدارس الذكية',
            'features': 'الميزات',
            'new': 'جديد',
            'Blogs': 'المدونات',
            'blog_left_sidebar': 'الشريط الجانبي الأيسر',
            'blog_right_sidebar': 'الشريط الجانبي الأيمن',
            'blog_detail': 'تفاصيل المدونة',
            'category_left_sidebar': 'الشريط الجانبي الأيسر',
            'category_right_sidebar': 'الشريط الجانبي الأيمن',
            'category_no_sidebar': 'بدون شريط جانبي',
            'category_metro': 'مترو',
            'category_full_width': 'عرض كامل',
            'Products': 'المنتجات',
            'left_sidebar': 'الشريط الجانبي الأيسر',
            'right_sidebar': 'الشريط الجانبي الأيمن',
            'no_sidebar': 'بدون شريط جانبي',
            'three_col_thumbnail_left': 'الصورة المصغرة اليسرى',
            'three_col_thumbnail_right': 'الصورة المصغرة اليمنى',
            'thumbnail_below': 'الصورة المصغرة أسفل',
            'accordian_details': 'تفاصيل الطي',
            'thumbnail_left': 'الصورة اليسرى',
            'thumbnail_right': 'الصورة اليمنى',
            'vertical_tab': 'تبويب عمودي',
            'Pages': 'الصفحات',
            'about_us': 'معلومات عنا',
            'lookbook': 'كتاب المظهر',
            'login': 'تسجيل الدخول',
            'register': 'تسجيل',
            'logout': 'تسجيل الخروج',
            'search': 'بحث',
            'wishlist': 'قائمة الأمنيات',
            'cart': 'عربة التسوق',
            'collection': 'المجموعة',
            'forget_password': 'نسيت كلمة المرور',
            'contact': 'اتصل',
            'checkout': 'إتمام الشراء',
            'compare': 'مقارنة',
            'order_success': 'نجاح الطلب',
            'dashboard': 'لوحة التحكم',
            'FAQ': 'الأسئلة الشائعة',
            'Shop': 'التسوق',
            'mens_fashion': 'موضة الرجال',
            'top': 'أعلى',
            'bottom': 'أسفل',
            'ethic_wear': 'الملابس التقليدية',
            'sports_wear': 'ملابس رياضية',
            'shirts': 'قمصان',
            'women_fashion': 'موضة النساء',
            'dresses': 'فساتين',
            'skirts': 'تنورات',
            'westarn_wear': 'ملابس غربية',
            'ethnic_wear': 'ملابس تقليدية',
            'sport_wear': 'ملابس رياضية',
            'bottom_wear': 'ملابس سفلية',
            'kids_fashion': 'موضة الأطفال',
            'accessories': 'الإكسسوارات',
            'fashion_jewellery': 'مجوهرات الموضة',
            'caps_and_hats': 'قبعات',
            'precious_jewellery': 'مجوهرات ثمينة',
            'necklaces': 'قلائد',
            'earrings': 'أقراط',
            'rings_wrist_wear': 'خواتم وأساور',
            'men_accessories': 'إكسسوارات الرجال',
            'ties': 'ربطات العنق',
            'cufflinks': 'أزرار الأكمام',
            'pockets_squares': 'مناديل الجيب',
            'helmets': 'خوذات',
            'scarves': 'أوشحة',
            'phone_cases': 'أغلفة الهاتف',
            'my_account': 'حسابي',
            'fashion': 'الموضة',
            'beauty': 'الجمال',
            'electronic': 'الإلكترونيات',
            'furniture': 'الأثاث',
            'kids': 'الأطفال',
            'pets': 'الحيوانات الأليفة',
            'vegetables': 'الخضروات',
            'watch': 'الساعات',
            'theme_elements': 'عناصر التصميم',
            'element_title': 'عنوان العنصر',
            'collection_banner': 'لافتة المجموعة',
            'home_slider': 'شريط التمرير الرئيسي',
            'category': 'الفئة',
            'service': 'الخدمة',
            'image_size_ratio': 'نسبة حجم الصورة',
            'product_elements': 'عناصر المنتج',
            'product_box': 'صندوق المنتج',
            'product_slider': 'شريط تمرير المنتج',
            'no_slider': 'بدون شريط تمرير',
            'multi_slider': 'شريط تمرير متعدد',
            'tab': 'تبويب',
            'email_template': 'قالب البريد الإلكتروني',
            'portfolio': 'الحافظة',
            'portfolio_grid_2': 'شبكة الحافظة 2',
            'portfolio_grid_3': 'شبكة الحافظة 3',
            'portfolio_grid_4': 'شبكة الحافظة 4',
            'portfolio_masonary_2': 'فسيفساء 2',
            'portfolio_masonary_3': 'فسيفساء 3',
            'portfolio_masonary_4': 'فسيفساء 4',
            'portfolio_masonary_full': 'فسيفساء بعرض كامل',
            'Books': 'كتب',
            'KNOW IT ALL FIRST!': 'تعرف على كل شيء أولا!',
            'Never Miss Anything Signing Up To Our Newsletter.': 'لا تفوت أي شيء عند الاشتراك في نشرتنا الإخبارية.',
            'subscribe': 'يشترك',
            'about': 'عن',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit , sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.': 'من المهم جدًا الاعتناء بالمريض، حتى نتمكن من دعم المريض، ولكن هذه المرة سيتأثر ببعض العمل العظيم والألم.',
            'my account': 'حسابي',
            'womens': 'للنساء',
            'clothing': 'ملابس',
            'accessories': 'مُكَمِّلات',
            'featured': 'مميزة',
            'why we choose': 'لماذا نختار',
            'shipping & return': 'الشحن والعودة',
            'secure shopping': 'التسوق الآمن',
            'gallary': 'معرض',
            'affiliates': 'الشركات التابعة',
            'contacts': 'اتصالات',
            'Edumalls Demo Store, Lucknow store India 100-659': 'متجر Edumalls التجريبي، متجر لكناو، الهند 100-659',
            'Call Us: 123-456-7898': 'اتصل بنا: 123-456-7898',
            'Email Us:': 'راسلنا عبر البريد الإلكتروني :',
            'store information': 'تخزين المعلومات',

        }
    }

},