export const homeProductData = [
    {
      brand: "زارا",
      category: "ملابس",
      stock: 10,
      description:
        "لكن الحاجة، قبل volputate volutpat، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
      images: [
        {
          img: card1,
          alt: "ورق",
        },
        {
          img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
          alt: "جانب حقيبة الظهر",
        },
      ],
      name: `ورق نسخ هامرميل كوبي بلس مقاس 8.5 بوصة × 11 بوصة، 20...`,
      averageRating: "4",
      revCount: "25123",
      discountPercent: "45% off",
      discount: 40,
      offer_price: 39.99,
      price: 76.99,
      rating: "4.5",
      slug: "حقيبة ظهر",
      status: "أُوكَازيُون",
      id: "1000",
    },
    {
      brand: "نايك",
      category: "أحذية",
      stock: 25,
      description:
        "حذاء جري مريح للارتداء طوال اليوم. مصنوعة من مواد متينة لتدوم لفترة أطول.",
      images: [
        {
          img: img1 ,
          alt: "جهاز عرض",
        },
        {
          img: "https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg",
          alt: "جانب من أحذية الجري",
        },
      ],
      name: `جهاز عرض TMY صغير، مشروع بلوتوث مطور-`,
      revCount: "41235",
      averageRating: "4",
      discountPercent: "56% off",
      discount: 20,
      offer_price: 76.99,
      price: 79.99,
      rating: "4.7",
      slug: "أحذية الجري",
      status: "جديد",
      id: "2000",
    },
    {
      brand: "أديداس",
      category: "مُكَمِّلات",
      stock: 15,
      description:
        "ساعة رياضية أنيقة مثالية للرياضيين والارتداء اليومي. مقاومة للماء وأنيقة.",
      images: [
        {
          img: card3,
          alt: "اسكتشات",
        },
        {
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoFRQjM-wM_nXMA03AGDXgJK3VeX7vtD3ctA&s",
          alt: "جانب الساعات الرياضية",
        },
      ],
      name: "أقلام رصاص ملونة ممتازة، عدد 24، ناعمة الملمس، متعددة الألوان",
      revCount: "21238",
      averageRating: "2",
      discountPercent: "87% off",
      discount: 20,
      offer_price: 11.99,
      price: 76.99,
      rating: "4.2",
      slug: "ساعة رياضية",
      status: "قمة",
      id: "3000",
    },
    {
      brand: "زارا",
      category: "ملابس",
      stock: 10,
      description:
        "لكن الحاجة، قبل volputate volutpat، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
      images: [
        {
          img: card4,
          alt: "",
        },
        {
          img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
          alt: "جانب حقيبة الظهر",
        },
      ],
      name: `اللون اللاسلكي Epson Workforce ES-500W II`,
      averageRating: "4",
      revCount: "25123",
      discountPercent: "49% off",
      discount: 40,
      offer_price: 319.27,
      price: 776.99,
      rating: "4.5",
      slug: "حقيبة ظهر",
      status: "أُوكَازيُون",
      id: "1200",
    },
    {
      brand: "اتش اند ام",
      category: "ملابس",
      stock: 50,
      description:
        "تي شيرت قطني مريح وأنيق مثالي للنزهات الكاجوال والارتداء اليومي.",
      images: [
        {
          img: card5,
          alt: "تي شيرت أمامي",
        },
        {
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-C_UAhXq9GfuGO452EEzfbKnh1viQB9EDBQ&s",
          alt: "تي شيرت الظهر",
        },
      ],
      name: "ابتكارات الإكسسوارات غرزة كاملة الحجم 16 بوصة",
      revCount: "66787",
      averageRating: "5",
      discountPercent: "77% off",
      discount: 30,
      offer_price: 27.99,
      price: 76.99,
      rating: "4.8",
      slug: "تي شيرت قطن",
      status: "أُوكَازيُون",
      id: "4000",
    },
    {
      brand: "يائس",
      category: "ملابس",
      stock: 20,
      description:
        "سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
      images: [
        {
          img: img2,
          alt: "سترة الشتاء الجبهة",
        },
        {
          img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
          alt: "سترة الشتاء مرة أخرى",
        },
      ],
      name: `شبكة/شبكة مريحة من سلسلة WorkPro 100`,
      revCount: "134458",
      averageRating: "2",
      discountPercent: "خصم 48%",
      discount: 150,
      offer_price: 39.99,
      price: 79.99,
      rating: "4.6",
      slug: "سترة الشتاء",
      status: "جديد",
      id: "6000",
    },
    // {
    //   brand: "Puma",
    //   category: "أحذية",
    //   stock: 30,
    //   description:
    //     "High-performance football boots designed for precision and comfort on the field.",
    //   images: [
    //     {
    //       img: "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    //       alt: "Football Boots Front",
    //     },
    //     {
    //       img: "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    //       alt: "Football Boots Side",
    //     },
    //   ],
    //   name: "ابتكارات الإكسسوارات غرزة كاملة الحجم 16 بوصة",
    //   revCount: "33453",
    //   averageRating: "3",
    //   discountPercent:"45% off",
    //   discount:100,
    //   offer_price: 50,
    //   price: 700,
    //   rating: "4.3",
    //   slug: "football-boots",
    //   status: "قمة",
    //   id: "5",
    // },
    // {
    //   brand: "يائس",
    //   category: "ملابس",
    //   stock: 20,
    //   description:
    //     "سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
    //   images: [
    //     {
    //       img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
    //       alt: "سترة الشتاء الجبهة",
    //     },
    //     {
    //       img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
    //       alt: "سترة الشتاء مرة أخرى",
    //     },
    //   ],
    //   name: `شبكة/شبكة مريحة من سلسلة WorkPro 100`,
    //   revCount: "134458",
    //   averageRating: "2",
    //   discountPercent:"45% off",
    //   discount:150,
    //   offer_price: 50,
    //   price: 200,
    //   rating: "4.6",
    //   slug: "سترة الشتاء",
    //   status: "جديد",
    //   id: "61",
    // },
  ];
  export const قمةRatingDataSlider = [
    {
      brand: "زارا",
      category: "ملابس",
      stock: 10,
      description:
        "لكن الحاجة، قبل volputate volutpat، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
      images: [
        {
          img: card2_1,
          alt: "ورق",
        },
        {
          img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
          alt: "جانب حقيبة الظهر",
        },
      ],
      name: `كمبيوتر محمول HP مقاس 15.6 بوصة، معالج AMD Ryzen 3، مُمكّن، سعة 8 جيجابايت`,
      averageRating: "4",
      revCount: "25123",
      discountPercent: "تخفيضات هائلة بخصم 48%",
      discount: 40,
      offer_price: 379.99,
      price: 76.99,
      rating: "4.5",
      slug: "حقيبة ظهر",
      status: "أُوكَازيُون",
      id: "100",
    },
    {
      brand: "نايك",
      category: "أحذية",
      stock: 25,
      description:
        "حذاء جري مريح للارتداء طوال اليوم. مصنوعة من مواد متينة لتدوم لفترة أطول.",
      images: [
        {
          img: card2_2,
          alt: "جهاز عرض",
        },
        {
          img: "https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg",
          alt: "جانب من أحذية الجري",
        },
      ],
      name: `Homenations 36 بوصة عرض خشب/- مكتب طلاب معدني مع`,
      revCount: "41235",
      averageRating: "4",
      discountPercent: "خصم 48%",
      discount: 20,
      offer_price: 76.99,
      price: 59.99,
      rating: "4.7",
      slug: "أحذية الجري",
      status: "جديد",
      id: "200",
    },
    {
      brand: "أديداس",
      category: "مُكَمِّلات",
      stock: 15,
      description:
        "ساعة رياضية أنيقة مثالية للرياضيين والارتداء اليومي. مقاومة للماء وأنيقة.",
      images: [
        {
          img: card2_3,
          alt: "اسكتشات",
        },
        {
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoFRQjM-wM_nXMA03AGDXgJK3VeX7vtD3ctA&s",
          alt: "جانب الساعات الرياضية",
        },
      ],
      name: "2025 دبابيس 5 × 8 أسبوعية وشهرية",
      revCount: "21238",
      averageRating: "2",
      discountPercent: "خصم 48%",
      discount: 20,
      offer_price: 11.99,
      price: 39.99,
      rating: "4.2",
      slug: "ساعة رياضية",
      status: "قمة",
      id: "300",
    },
    {
      brand: "زارا",
      category: "ملابس",
      stock: 10,
      description:
        "لكن الحاجة، قبل وفولبوتات فولوتبات، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
      images: [
        {
          img: card2_4,
          alt: "",
        },
        {
          img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
          alt: "جانب حقيبة الظهر",
        },
      ],
      name: `تابلت لينوفو تاب M11 بوصة فل اتش دي ال سي دي، 1920 × 1200، MTK`,
      averageRating: "4",
      revCount: "25123",
      discountPercent: "حصري",
      discount: 40,
      offer_price: 199.27,
      price: 199.99,
      rating: "4.5",
      slug: "حقيبة ظهر",
      status: "أُوكَازيُون",
      id: "400",
    },
    {
      brand: "اتش اند ام",
      category: "ملابس",
      stock: 50,
      description:
        "تي شيرت قطني مريح وأنيق مثالي للنزهات الكاجوال والارتداء اليومي.",
      images: [
        {
          img: img1,
          alt: "تي شيرت أمامي",
        },
        {
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-C_UAhXq9GfuGO452EEzfbKnh1viQB9EDBQ&s",
          alt: "تي شيرت الظهر",
        },
      ],
      name: "أنابيب وعلب الطلاء الزيتي غير الكاملة لفناني أوتريخت",
      revCount: "66787",
      averageRating: "5",
      discountPercent: "خصم 48%",
      discount: 30,
      offer_price: 9.99,
      price: 7.99,
      rating: "4.8",
      slug: "تي شيرت قطن",
      status: "أُوكَازيُون",
      id: "500",
    },
    {
      brand: "يائس",
      category: "ملابس",
      stock: 20,
      description:
        "سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
      images: [
        {
          img: img1,
          alt: "سترة الشتاء الجبهة",
        },
        {
          img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
          alt: "سترة الشتاء مرة أخرى",
        },
      ],
      name: `غزل ترايت تكس جامبو المتجول، غزل جامبو متجول`,
      revCount: "134458",
      averageRating: "2",
      discountPercent: "خصم 48%",
      discount: 150,
      offer_price: 79.99,
      price: 39.99,
      rating: "4.6",
      slug: "سترة الشتاء",
      status: "جديد",
      id: "600",
    },
    // {
    //   brand: "Puma",
    //   category: "أحذية",
    //   stock: 30,
    //   description:
    //     "High-performance football boots designed for precision and comfort on the field.",
    //   images: [
    //     {
    //       img: "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    //       alt: "Football Boots Front",
    //     },
    //     {
    //       img: "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    //       alt: "Football Boots Side",
    //     },
    //   ],
    //   name: "Accessory Innovations Stitch Full Size 16 Inch",
    //   revCount: "33453",
    //   averageRating: "3",
    //   discountPercent:"45% off",
    //   discount:100,
    //   offer_price: 50,
    //   price: 700,
    //   rating: "4.3",
    //   slug: "football-boots",
    //   status: "قمة",
    //   id: "5",
    // },
    // {
    //   brand: "يائس",
    //   category: "ملابس",
    //   stock: 20,
    //   description:
    //     "سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
    //   images: [
    //     {
    //       img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
    //       alt: "سترة الشتاء الجبهة",
    //     },
    //     {
    //       img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
    //       alt: "سترة الشتاء مرة أخرى",
    //     },
    //   ],
    //   name: `WorkPro 100 Series Ergonomic Mesh/Mesh`,
    //   revCount: "134458",
    //   averageRating: "2",
    //   discountPercent:"45% off",
    //   discount:150,
    //   offer_price: 50,
    //   price: 200,
    //   rating: "4.6",
    //   slug: "سترة الشتاء",
    //   status: "جديد",
    //   id: "61",
    // },
  ];
  export const essentialDealDataSlider = [
    {
      brand: "زارا",
      category: "ملابس",
      stock: 10,
      description:
        "لكن الحاجة، قبل وفولبوتات فولوتبات، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
      images: [
        {
          img: card3_1,
          alt: "ورق",
        },
        {
          img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
          alt: "جانب حقيبة الظهر",
        },
      ],
      name: `كمبيوتر محمول HP مقاس 15.6 بوصة، معالج AMD Ryzen 3، مُمكّن، سعة 8 جيجابايت`,
      averageRating: "4",
      revCount: "25123",
      discountPercent: "8% off",
      discount: 40,
      offer_price: 379.99,
      price: 76.99,
      rating: "4.5",
      slug: "حقيبة ظهر",
      status: "أُوكَازيُون",
      id: "10",
    },
    {
      brand: "نايك",
      category: "أحذية",
      stock: 25,
      description:
        "حذاء جري مريح للارتداء طوال اليوم. مصنوعة من مواد متينة لتدوم لفترة أطول.",
      images: [
        {
          img: card3_2,
          alt: "جهاز عرض",
        },
        {
          img: "https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg",
          alt: "أحذية الجري الجانبية",
        },
      ],
      name: `Homenations 36 بوصة عرض خشب/- مكتب طلاب معدني مع`,
      revCount: "41235",
      averageRating: "4",
      discountPercent: "خصم 19%",
      discount: 20,
      offer_price: 76.99,
      price: 59.99,
      rating: "4.7",
      slug: "أحذية الجري",
      status: "جديد",
      id: "20",
    },
    {
      brand: "أديداس",
      category: "مُكَمِّلات",
      stock: 15,
      description:
        "ساعة رياضية أنيقة مثالية للرياضيين والارتداء اليومي. مقاومة للماء وأنيقة.",
      images: [
        {
          img: card3_3,
          alt: "اسكتشات",
        },
        {
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoFRQjM-wM_nXMA03AGDXgJK3VeX7vtD3ctA&s",
          alt: "جانب الساعات الرياضية",
        },
      ],
      name: "2025 دبابيس 5 × 8 أسبوعية وشهرية",
      revCount: "21238",
      averageRating: "2",
      discountPercent: "خصم 48%",
      discount: 20,
      offer_price: 11.99,
      price: 39.99,
      rating: "4.2",
      slug: "ساعة رياضية",
      status: "قمة",
      id: "30",
    },
    {
      brand: "زارا",
      category: "ملابس",
      stock: 10,
      description:
        "لكن الحاجة، قبل وفولبوتات فولوتبات، إيروس هي دائما في القدم، والخوف من أحزان الحياة دعاية مجانية للاتحاد الأوروبي. نقية خالية من الأمراض، طعم adipiscing. لكن السرير",
      images: [
        {
          img: card3_4,
          alt: "",
        },
        {
          img: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?cs=srgb&dl=pexels-madebymath-90946.jpg&fm=jpg",
          alt: "جانب حقيبة الظهر",
        },
      ],
      name: `لوازم الحرف الخشبية`,
      averageRating: "4",
      revCount: "25123",
      discountPercent: "18% off",
      discount: 40,
      offer_price: 199.27,
      price: 199.99,
      rating: "4.5",
      slug: "حقيبة ظهر",
      status: "أُوكَازيُون",
      id: "30",
    },
    {
      brand: "اتش اند ام",
      category: "ملابس",
      stock: 50,
      description:
        "تي شيرت قطني مريح وأنيق مثالي للنزهات الكاجوال والارتداء اليومي.",
      images: [
        {
          img: card3_5,
          alt: "تي شيرت أمامي",
        },
        {
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-C_UAhXq9GfuGO452EEzfbKnh1viQB9EDBQ&s",
          alt: "تي شيرت الظهر",
        },
      ],
      name: "أنابيب وعلب الطلاء الزيتي غير الكاملة لفناني أوتريخت",
      revCount: "66787",
      averageRating: "5",
      discountPercent: "خصم 48%",
      discount: 30,
      offer_price: 9.99,
      price: 7.99,
      rating: "4.8",
      slug: "تي شيرت قطن",
      status: "أُوكَازيُون",
      id: "40",
    },
    {
      brand: "يائس",
      category: "ملابس",
      stock: 20,
      description:
        "سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
      images: [
        {
          img: card3_6,
          alt: "سترة الشتاء الجبهة",
        },
        {
          img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
          alt: "سترة الشتاء مرة أخرى",
        },
      ],
      name: `خيوط ترايت تكس جامبو المتجولة`,
      revCount: "134458",
      averageRating: "2",
      discountPercent: "خصم 48%",
      discount: 150,
      offer_price: 79.99,
      price: 39.99,
      rating: "4.6",
      slug: "سترة الشتاء",
      status: "جديد",
      id: "60",
    },
    // {
    //   brand: "Puma",
    //   category: "أحذية",
    //   stock: 30,
    //   description:
    //     "High-performance football boots designed for precision and comfort on the field.",
    //   images: [
    //     {
    //       img: "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    //       alt: "Football Boots Front",
    //     },
    //     {
    //       img: "https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp",
    //       alt: "Football Boots Side",
    //     },
    //   ],
    //   name: "Accessory Innovations Stitch Full Size 16 Inch",
    //   revCount: "33453",
    //   averageRating: "3",
    //   discountPercent:"45% off",
    //   discount:100,
    //   offer_price: 50,
    //   price: 700,
    //   rating: "4.3",
    //   slug: "football-boots",
    //   status: "قمة",
    //   id: "5",
    // },
    // {
    //   brand: "يائس",
    //   category: "ملابس",
    //   stock: 20,
    //   description:
    //     "سترة شتوية أنيقة مصنوعة من مواد فاخرة لتمنحك الدفء والراحة.",
    //   images: [
    //     {
    //       img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
    //       alt: "سترة الشتاء الجبهة",
    //     },
    //     {
    //       img: "https://cdn3.pixelcut.app/7/20/uncrop_hero_bdf08a8ca6.jpg",
    //       alt: "سترة الشتاء مرة أخرى",
    //     },
    //   ],
    //   name: `WorkPro 100 Series Ergonomic Mesh/Mesh`,
    //   revCount: "134458",
    //   averageRating: "2",
    //   discountPercent:"45% off",
    //   discount:150,
    //   offer_price: 50,
    //   price: 200,
    //   rating: "4.6",
    //   slug: "سترة الشتاء",
    //   status: "جديد",
    //   id: "61",
    // },
  ];